apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-persist
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    ## server: fs-xxxxxx.efs.<cluster-region>.amazonaws.com
    server: fs-0799fda4aeef292f0.efs.us-west-2.amazonaws.com
    path: "/"
