## <cognito-client-id>
## <cognito-client-secret>

jupyterhub:
  proxy:
    secretToken: (1)
  hub:
    services:
      dask-gateway:
        apiToken: (2)
    config:
      GenericOAuthenticator:
        client_id: <cognito-client-id>
        client_secret: <cognito-client-secret>

dask-gateway:
  gateway:
    auth:
      jupyterhub:
        apiToken: (2)
